using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Extensions.Ai.SourceGenerators;

/// <summary>
/// Source generator that creates JSON serialization context for AI prompts and responses.
/// This enables AOT compilation support by pre-generating serialization code.
/// </summary>
[Generator]
public class AiJsonSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes that inherit from Prompt<T>
        var promptClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidatePromptClass(node),
                transform: static (ctx, _) => GetPromptClassInfo(ctx))
            .Where(static info => info is not null);

        // Combine and generate
        var compilation = context.CompilationProvider.Combine(promptClasses.Collect());
        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidatePromptClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList != null
               && classDecl.BaseList.Types.Any();
    }

    private static PromptClassInfo? GetPromptClassInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Skip abstract classes
        if (classSymbol.IsAbstract)
            return null;

        // Check if it inherits from PromptBase<T>
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.IsGenericType)
            {
                var baseName = baseType.ConstructedFrom.Name;
                if (baseName == "PromptBase" && baseType.TypeArguments.Length == 1)
                {
                    var responseType = baseType.TypeArguments[0];
                    return new PromptClassInfo(
                        ClassName: classSymbol.Name,
                        FullClassName: classSymbol.ToDisplayString(),
                        Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
                        ResponseTypeName: responseType.Name,
                        ResponseTypeFullName: responseType.ToDisplayString()
                    );
                }
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<PromptClassInfo?> prompts, SourceProductionContext context)
    {
        var validPrompts = prompts.Where(p => p is not null).Cast<PromptClassInfo>().ToList();

        if (validPrompts.Count == 0)
            return;

        // Generate JsonSerializerContext for all response types
        var responseTypes = validPrompts
            .Select(p => p.ResponseTypeFullName)
            .Distinct()
            .ToList();

        var source = GenerateJsonSerializerContext(responseTypes, validPrompts);
        context.AddSource("AiJsonSerializerContext.g.cs", source);
    }

    private static string GenerateJsonSerializerContext(List<string> responseTypes, List<PromptClassInfo> prompts)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Extensions.Ai;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated JSON serialization context for AOT support.");
        sb.AppendLine("/// Contains serialization metadata for all prompt response types.");
        sb.AppendLine("/// </summary>");

        // Add JsonSerializable attributes for each response type
        foreach (var responseType in responseTypes)
        {
            sb.AppendLine($"[JsonSerializable(typeof({responseType}))]");
        }

        // Add common types
        sb.AppendLine("[JsonSerializable(typeof(string))]");
        sb.AppendLine("[JsonSerializable(typeof(int))]");
        sb.AppendLine("[JsonSerializable(typeof(bool))]");
        sb.AppendLine("[JsonSerializable(typeof(double))]");
        sb.AppendLine("[JsonSerializable(typeof(float[]))]");

        sb.AppendLine("[JsonSourceGenerationOptions(");
        sb.AppendLine("    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,");
        sb.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("    PropertyNameCaseInsensitive = true)]");
        sb.AppendLine("public partial class AiJsonSerializerContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("    // ------------------------------------------------------------------");
        sb.AppendLine("    // .NET 10 removed the parameterless JsonSerializerContext() ctor;");
        sb.AppendLine("    // the only base ctor now is JsonSerializerContext(JsonSerializerOptions?).");
        sb.AppendLine("    // We must therefore declare explicit ctors that delegate to it, otherwise");
        sb.AppendLine("    // CS7036 'no argument given for required parameter options' is emitted.");
        sb.AppendLine("    //");
        sb.AppendLine("    // .NET 10 also turned JsonSerializerContext.GetTypeInfo(Type) and");
        sb.AppendLine("    // GeneratedSerializerOptions into ABSTRACT members. The System.Text.Json");
        sb.AppendLine("    // source generator normally provides these overrides via partial-class");
        sb.AppendLine("    // merge, but Roslyn source generators cannot observe files emitted by");
        sb.AppendLine("    // other generators in the same compilation, so STJ never sees this");
        sb.AppendLine("    // declaration and never emits the overrides for it. We supply");
        sb.AppendLine("    // reflection-based fallbacks so the type compiles cleanly on .NET 10.");
        sb.AppendLine("    // Consumers can still extend this partial class in their own assembly");
        sb.AppendLine("    // to opt into a fully AOT-friendly context.");
        sb.AppendLine("    // ------------------------------------------------------------------");
        sb.AppendLine("    public AiJsonSerializerContext() : base(null) { }");
        sb.AppendLine("    public AiJsonSerializerContext(System.Text.Json.JsonSerializerOptions? options) : base(options) { }");
        sb.AppendLine();
        sb.AppendLine("#if NET10_0_OR_GREATER");
        sb.AppendLine("    public override System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(System.Type type) => null;");
        sb.AppendLine("    protected override System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => null;");
        sb.AppendLine("#endif");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record PromptClassInfo(
        string ClassName,
        string FullClassName,
        string Namespace,
        string ResponseTypeName,
        string ResponseTypeFullName
    );
}
