using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Extensions.Ai.SourceGenerators;

/// <summary>
/// Source generator that auto-registers AI providers from loaded assemblies.
/// Generates AddAiProviders extension method that registers all providers.
/// </summary>
[Generator]
public class AiProviderRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes that implement IModelProvider
        var providerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateProviderClass(node),
                transform: static (ctx, _) => GetProviderClassInfo(ctx))
            .Where(static info => info is not null);

        var compilation = context.CompilationProvider.Combine(providerClasses.Collect());
        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateProviderClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList != null
               && classDecl.BaseList.Types.Any();
    }

    private static ProviderClassInfo? GetProviderClassInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Skip abstract classes
        if (classSymbol.IsAbstract)
            return null;

        // Check if implements IModelProvider
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.Name == "IModelProvider")
            {
                return new ProviderClassInfo(
                    ClassName: classSymbol.Name,
                    FullClassName: classSymbol.ToDisplayString(),
                    Namespace: classSymbol.ContainingNamespace.ToDisplayString()
                );
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ProviderClassInfo?> providers, SourceProductionContext context)
    {
        var validProviders = providers.Where(p => p is not null).Cast<ProviderClassInfo>().ToList();

        if (validProviders.Count == 0)
            return;

        var source = GenerateProviderRegistration(validProviders);
        context.AddSource("AiProviderRegistration.g.cs", source);
    }

    private static string GenerateProviderRegistration(List<ProviderClassInfo> providers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Extensions.Ai;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated provider registration extension.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class AiProviderRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all discovered AI providers.");
        sb.AppendLine("    /// This method is auto-generated by source generator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddDiscoveredAiProviders(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var provider in providers)
        {
            sb.AppendLine($"        services.AddSingleton<IModelProvider, {provider.FullClassName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record ProviderClassInfo(
        string ClassName,
        string FullClassName,
        string Namespace
    );
}
