using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Extensions.Ai.SourceGenerators;

/// <summary>
/// Source generator that discovers every concrete subclass of
/// <c>ToolBase&lt;TInput, TOutput&gt;</c> in the current compilation and emits
/// an <c>AddAiTools()</c> extension method that registers each one via
/// <c>AddAiTool&lt;T&gt;()</c>.
/// </summary>
/// <remarks>
/// Mirrors the pattern of <see cref="AiProviderRegistrationGenerator"/>.
/// Skips abstract types and generic open types.
/// </remarks>
[Generator]
public class AiToolRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toolClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateToolClass(node),
                transform: static (ctx, _) => GetToolClassInfo(ctx))
            .Where(static info => info is not null);

        var compilation = context.CompilationProvider.Combine(toolClasses.Collect());
        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateToolClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList != null
               && classDecl.BaseList.Types.Any();
    }

    private static ToolClassInfo? GetToolClassInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Skip abstract and open-generic tools.
        if (classSymbol.IsAbstract || classSymbol.IsGenericType)
            return null;

        // Walk base type chain searching for ToolBase<,>.
        var current = classSymbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.Name == "ToolBase"
                && current.ContainingNamespace?.ToDisplayString() == "Zonit.Extensions.Ai")
            {
                return new ToolClassInfo(
                    ClassName: classSymbol.Name,
                    FullClassName: classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    Namespace: classSymbol.ContainingNamespace.ToDisplayString()
                );
            }

            current = current.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ToolClassInfo?> tools, SourceProductionContext context)
    {
        var validTools = tools.Where(t => t is not null).Cast<ToolClassInfo>()
            // Distinct by FullClassName in case of partial classes or duplicate syntax nodes.
            .GroupBy(t => t.FullClassName)
            .Select(g => g.First())
            .OrderBy(t => t.FullClassName, StringComparer.Ordinal)
            .ToList();

        // Always emit the file — even with zero tools — so AddAiTools() exists
        // and compiles (prevents cryptic "does not exist" errors in user code).
        var source = GenerateToolRegistration(validTools);
        context.AddSource("AiToolRegistration.g.cs", source);
    }

    private static string GenerateToolRegistration(List<ToolClassInfo> tools)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Extensions.Ai.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated tool announcer. The module initializer below registers");
        sb.AppendLine("    /// every discovered ToolBase&lt;,&gt; type with");
        sb.AppendLine("    /// <see cref=\"global::Zonit.Extensions.Ai.ToolDiscovery\"/> at assembly load time,");
        sb.AppendLine("    /// so a single <c>services.AddAi()</c> call wires them all up automatically.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class AiToolModuleInit");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Init()");
        sb.AppendLine("        {");

        if (tools.Count == 0)
        {
            sb.AppendLine("            // No ToolBase<,> implementations discovered in this compilation.");
        }
        else
        {
            foreach (var tool in tools)
            {
                sb.AppendLine($"            global::Zonit.Extensions.Ai.ToolDiscovery.Register(typeof({tool.FullClassName}));");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Backwards-compatible alias kept for code that explicitly calls");
        sb.AppendLine("    /// <c>services.AddAiTools()</c>. Since v1.21 every tool type is announced");
        sb.AppendLine("    /// to <c>ToolDiscovery</c> via a module initializer and registered");
        sb.AppendLine("    /// automatically by <c>AddAi()</c> — this method is now a no-op.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.Obsolete(\"Tools are auto-registered by AddAi() since v1.21. This call is now a no-op and can be removed.\", false)]");
        sb.AppendLine("    public static class AiToolRegistrationExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>No-op alias — see class summary.</summary>");
        sb.AppendLine("        public static IServiceCollection AddAiTools(this IServiceCollection services) => services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed record ToolClassInfo(
        string ClassName,
        string FullClassName,
        string Namespace
    );
}
