using System.Globalization;
using System.Reflection;
using System.Text;
using Xunit;
using Zonit.Extensions.Ai;
using IODirectory = System.IO.Directory;
using IODirectoryInfo = System.IO.DirectoryInfo;
using IOFile = System.IO.File;
using IOPath = System.IO.Path;

namespace Zonit.Extensions.Ai.Tests.Models;

/// <summary>
/// Generates <c>Instruction/llms.md</c> from the real model types
/// (provider, context window, modalities, capabilities, price incl. cache) and
/// fails if the committed file is stale — regenerating it in the process.
/// <para>
/// This is the always-fresh "which model does what / costs what" catalog: it is
/// derived from code by reflection, so it can never drift like a hand-maintained
/// list. Adding a new provider package (and its project reference here)
/// automatically expands the catalog on the next test run.
/// </para>
/// </summary>
public class ModelCatalogTests
{
    private const string CatalogFileName = "llms.md";

    // Provider assemblies to reflect over. Each must be referenced by this test
    // project (see the .csproj) so it is present in the output directory.
    private static readonly string[] ProviderSuffixes =
    [
        "OpenAi", "Anthropic", "Google", "X", "Mistral", "DeepSeek", "Cohere",
        "Baidu", "Groq", "Moonshot", "Zhipu", "Alibaba", "Yi", "Together",
        "Fireworks", "Perplexity",
    ];

    [Fact]
    public void Catalog_IsUpToDate()
    {
        var generated = BuildCatalog();
        var path = LocateCatalogPath();

        var existing = IOFile.Exists(path) ? IOFile.ReadAllText(path) : null;
        if (Normalize(existing) != Normalize(generated))
        {
            IOFile.WriteAllText(path, generated);
            Assert.Fail(
                $"Instruction/{CatalogFileName} was missing or stale and has been regenerated at:\n  {path}\n" +
                "Review the diff and commit it, then re-run the tests.");
        }
    }

    private static string? Normalize(string? s) => s?.Replace("\r\n", "\n").TrimEnd();

    private sealed record Entry(string Provider, string Class, ILlm Model);

    private static string BuildCatalog()
    {
        var entries = new List<Entry>();

        foreach (var suffix in ProviderSuffixes)
        {
            Assembly asm;
            try { asm = Assembly.Load($"Zonit.Extensions.Ai.{suffix}"); }
            catch { continue; }

            foreach (var t in LoadableTypes(asm))
            {
                if (t is null || t.IsAbstract || !t.IsClass) continue;
                if (!typeof(ILlm).IsAssignableFrom(t)) continue;
                if (t.GetConstructor(Type.EmptyTypes) is null) continue;

                ILlm instance;
                try { instance = (ILlm)Activator.CreateInstance(t)!; }
                catch { continue; }

                entries.Add(new Entry(suffix, t.Name, instance));
            }
        }

        var sb = new StringBuilder();
        sb.Append("# Model catalog (generated)\n\n");
        sb.Append("> Auto-generated by `ModelCatalogTests.Catalog_IsUpToDate` from the actual model\n");
        sb.Append("> types — do not edit by hand; run the tests to refresh. Capabilities come from the\n");
        sb.Append("> interfaces each model implements. Prices are USD per 1M tokens; `—` means the\n");
        sb.Append("> model does not expose that price (e.g. no prompt caching on that model).\n");
        sb.Append("> A `⚠️` next to a class marks a model declared `[Obsolete]` (deprecated / being\n");
        sb.Append("> retired) — see the Deprecated models section at the end for the reason.\n\n");
        sb.Append($"Total: {entries.Count} models across {entries.Select(e => e.Provider).Distinct().Count()} providers.\n\n");

        foreach (var group in entries.GroupBy(e => e.Provider).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var ordered = group.OrderBy(e => e.Class, StringComparer.Ordinal).ToList();

            sb.Append($"## {group.Key}\n\n");

            sb.Append("### Capabilities & limits\n\n");
            sb.Append("| Class | Model name | Context | Max output | Modalities (in → out) | Capabilities | Tools |\n");
            sb.Append("| :--- | :--- | ---: | ---: | :--- | :--- | :--- |\n");
            foreach (var e in ordered)
            {
                var m = e.Model;
                var flag = IsObsolete(m.GetType()) ? " ⚠️" : "";
                sb.Append($"| `{e.Class}`{flag} | `{m.Name}` | {Tokens(m.MaxInputTokens)} | {Tokens(m.MaxOutputTokens)} | {m.Input} → {m.Output} | {Capabilities(m.GetType())} | {ToolsList(m.SupportedTools)} |\n");
            }
            sb.Append('\n');

            sb.Append("### Pricing — USD / 1M tokens\n\n");
            sb.Append("| Class | Input | Cached read | Cached write | Output |\n");
            sb.Append("| :--- | ---: | ---: | ---: | ---: |\n");
            foreach (var e in ordered)
            {
                var m = e.Model;
                sb.Append($"| `{e.Class}` | {Money(m.PriceInput)} | {Money(ReadDecimal(m, "PriceCachedInput"))} | {Money(ReadDecimal(m, "PriceCachedInputWrite"))} | {Money(m.PriceOutput)} |\n");
            }
            sb.Append('\n');
        }

        var deprecated = entries
            .Where(e => IsObsolete(e.Model.GetType()))
            .OrderBy(e => e.Provider, StringComparer.Ordinal)
            .ThenBy(e => e.Class, StringComparer.Ordinal)
            .ToList();
        if (deprecated.Count > 0)
        {
            sb.Append("## Deprecated models\n\n");
            sb.Append("These carry `[Obsolete]` in the SDK — avoid in new code; they may stop working.\n\n");
            sb.Append("| Provider | Class | Model name | Reason |\n");
            sb.Append("| :--- | :--- | :--- | :--- |\n");
            foreach (var e in deprecated)
                sb.Append($"| {e.Provider} | `{e.Class}` | `{e.Model.Name}` | {Sanitize(ObsoleteReason(e.Model.GetType()))} |\n");
            sb.Append('\n');
        }

        return sb.ToString();
    }

    private static IEnumerable<Type?> LoadableTypes(Assembly asm)
    {
        try { return asm.GetTypes(); }
        catch (ReflectionTypeLoadException ex) { return ex.Types; }
    }

    private static string Tokens(int count) =>
        count <= 0 ? "—" : count.ToString("#,0", CultureInfo.InvariantCulture);

    private static string ToolsList(ToolsType tools) =>
        tools == ToolsType.None ? "—" : tools.ToString();

    private static bool IsObsolete(Type t) => t.GetCustomAttribute<ObsoleteAttribute>() is not null;

    private static string? ObsoleteReason(Type t) => t.GetCustomAttribute<ObsoleteAttribute>()?.Message;

    private static string Sanitize(string? s) =>
        string.IsNullOrEmpty(s) ? "—" : s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");

    private static string Money(decimal? value) =>
        value is null ? "—" : "$" + value.Value.ToString("0.####", CultureInfo.InvariantCulture);

    private static decimal? ReadDecimal(object instance, string property)
    {
        var prop = instance.GetType().GetProperty(property);
        if (prop is null) return null;
        if (prop.PropertyType != typeof(decimal) && prop.PropertyType != typeof(decimal?)) return null;
        try { return (decimal?)prop.GetValue(instance); }
        catch { return null; }
    }

    private static string Capabilities(Type t)
    {
        var caps = new List<string>();
        void Add(string label, Type iface)
        {
            if (iface.IsAssignableFrom(t)) caps.Add(label);
        }

        Add("chat", typeof(ITextLlm));
        Add("agent", typeof(IAgentLlm));
        Add("reasoning", typeof(IReasoningLlm));
        Add("image", typeof(IImageLlm));
        Add("video", typeof(IVideoLlm));
        Add("embedding", typeof(IEmbeddingLlm));
        Add("audio", typeof(IAudioLlm));
        Add("fast", typeof(IFast));

        return caps.Count == 0 ? "—" : string.Join(", ", caps);
    }

    private static string LocateCatalogPath()
    {
        var dir = new IODirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = IOPath.Combine(dir.FullName, "Instruction");
            if (IODirectory.Exists(candidate))
                return IOPath.Combine(candidate, CatalogFileName);
            dir = dir.Parent;
        }

        throw new DirectoryNotFoundException(
            "Could not locate the 'Instruction' folder above the test output directory.");
    }
}
