using System.Text.Json.Serialization;

namespace Zonit.Extensions.Ai.OpenAi;

/// <summary>
/// AOT-safe <see cref="JsonSerializerContext"/> for OpenAI provider DTOs.
/// Generated by STJ at build time; wired into <c>OpenAiProvider</c>'s
/// <c>JsonOptions.TypeInfoResolverChain</c>.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(OpenAiResponse))]
[JsonSerializable(typeof(OpenAiOutput))]
[JsonSerializable(typeof(OpenAiContent))]
[JsonSerializable(typeof(OpenAiUsage))]
[JsonSerializable(typeof(OpenAiTokenDetails))]
[JsonSerializable(typeof(ImageResponse))]
[JsonSerializable(typeof(ImageData))]
[JsonSerializable(typeof(EmbeddingResponse))]
[JsonSerializable(typeof(EmbeddingData))]
[JsonSerializable(typeof(EmbeddingUsage))]
[JsonSerializable(typeof(StreamChunk))]
[JsonSerializable(typeof(StreamDelta))]
[JsonSerializable(typeof(TranscriptionResponse))]
[JsonSerializable(typeof(OpenAiResponsesRequest))]
[JsonSerializable(typeof(OpenAiInputItem))]
[JsonSerializable(typeof(OpenAiContentPart))]
[JsonSerializable(typeof(OpenAiTextConfig))]
[JsonSerializable(typeof(OpenAiTextFormat))]
[JsonSerializable(typeof(OpenAiReasoningConfig))]
[JsonSerializable(typeof(OpenAiToolItem))]
[JsonSerializable(typeof(OpenAiRankingOptions))]
[JsonSerializable(typeof(OpenAiImageRequest))]
[JsonSerializable(typeof(OpenAiEmbedRequest))]
internal sealed partial class OpenAiJsonContext : JsonSerializerContext
{
}
