using System.Text.Json.Serialization;

namespace Zonit.Extensions.Ai.ElevenLabs;

/// <summary>
/// AOT-safe <see cref="JsonSerializerContext"/> for ElevenLabs provider DTOs.
/// Generated by STJ at build time and used directly by <c>ElevenLabsProvider</c>.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(ElevenTtsRequest))]
[JsonSerializable(typeof(ElevenVoiceSettings))]
internal sealed partial class ElevenLabsJsonContext : JsonSerializerContext
{
}
